#!/usr/bin/env php
<?php

$framework = require_once __DIR__ . '/bootstrap/start.php';

$app = $framework->getDI()->get('console');

$settings = $framework->profile->getSettings();

// Settings
$app->setName($settings['application']['cli_name']);
$app->setVersion($settings['application']['version']);

// Add commands
$loader = $framework->getDI()->get('commandloader');
$loader->fromArray($settings['commands']);

$app->run();
