#!/usr/bin/env php
<?php

$framework = require_once __DIR__ . '/bootstrap/start.php';

$app = $framework->getDI()->get('console');
$app->setName('Wasp');
$app->setVersion('v0.1.0');

$settings = $framework->profile->getSettings();

// Add commands
$loader = $framework->getDI()->get('commandloader');
$loader->fromArray($settings['commands']);

$app->run();
